### PR TITLE
Migrate CKB docs

### PR DESCRIPTION
**Pull request by doitian**

### CODE REVIEW

**Comment by xxuejie** [comment]
I was thinking we could use some reorganization, for example:

* merkle tree, blake2b, transaction hash can all just be entries in the glossary
* `ckb-core-dev` and `ckb-debugging`, `ckb-on-windows` can all just be combined into a build guide
* `get-ckb`, `integrety-check` and `run-ckb-with-docker` can be integrated into existing running guides
* `Memo` and many of the rest articles can just be combined into an FAQ

@zengbing15 Will you be available to run through the documents here and do some reorganization?

**Comment by zengbing15** [comment]
> I was thinking we could use some reorganization, for example:
> 
> * merkle tree, blake2b, transaction hash can all just be entries in the glossary
> * `ckb-core-dev` and `ckb-debugging`, `ckb-on-windows` can all just be combined into a build guide
> * `get-ckb`, `integrety-check` and `run-ckb-with-docker` can be integrated into existing running guides
> * `Memo` and many of the rest articles can just be combined into an FAQ
> 
> @zengbing15 Will you be available to run through the documents here and do some reorganization?

ok, got it.

**Comment by doitian** [comment]
get-ckb.md also contains build guides for *nix systems

**Comment by zengbing15** [comment]
I find that[Error codes](https://github.com/nervosnetwork/ckb/wiki/How-to-sign-transaction) and How to sign transaction[How to sign transaction](https://github.com/nervosnetwork/ckb/wiki/How-to-sign-transaction) are missing in the PR, I think these two documents should be migrated too? @doitian

**Comment by zengbing15** [comment]
I don’t have a computer with windows system, so I can’t test “Build ckb on windows” now, I will add the tutorial first.

**Comment by doitian** [comment]
> [Error codes](https://github.com/nervosnetwork/ckb/wiki/How-to-sign-transaction) and [How to sign transaction](https://github.com/nervosnetwork/ckb/wiki/How-to-sign-transaction) are missing in the PR, I think these two documents should be migrated too? @doitian

These two articles are not in ckb wiki so I don't move them in.

**Comment by zengbing15** [comment]
> > [Error codes](https://github.com/nervosnetwork/ckb/wiki/How-to-sign-transaction) and [How to sign transaction](https://github.com/nervosnetwork/ckb/wiki/How-to-sign-transaction) are missing in the PR, I think these two documents should be migrated too? @doitian
> 
> These two articles are not in ckb wiki so I don't move them in.

got it.

**Comment by zengbing15** [comment]
CKB docs have been migrated, please review. I'm not sure how to solve the conflicting files. @xxuejie

**Review by xxuejie — APPROVED** [review]

**Pull request merged**
